Load OAUTH refresh tokens from 'pass' into systemctl env

diff --git a/bin/gmail-oauth2-token b/bin/gmail-oauth2-token
--- a/bin/gmail-oauth2-token
+++ b/bin/gmail-oauth2-token
@@ -1,23 +1,28 @@
 #!/bin/bash
 # retrieve an access token to gmail.
+# expected environment variables:
+#   OAUTH_CLIENT_SECRET  -  the oauth2 client secret.
+#     can be retrieved from here at any time:
+#       https://console.cloud.google.com/apis/credentials
+#   OAUTH_REFRESH_TOKEN_${account}
+#     the refresh token for the given account.
+
 set -eo pipefail
 
 # Google oauth2 info. Can be retrieved from here at any time:
 # https://console.cloud.google.com/apis/credentials
 OAUTH_CLIENT_ID='153322685357-4rjb09o5go4r1f7elcggc35jrgkdrnk2.apps.googleusercontent.com'
-OAUTH_CLIENT_SECRET=
+
+if [[ -z "$OAUTH_CLIENT_SECRET" ]]; then
+	echo >&2 'OAUTH_CLIENT_SECRET not set.'
+	exit 1
+fi
 
 # accounts
 accounts=(felix sylo)
 
 accounts_felix_user=felixschlitter@gmail.com
 accounts_sylo_user=felix@sylo.io
-
-# XXX these are sensitive. we must not keep them here! perhaps in an ENV var?
-#     like: GMAIL_OAUTH2_REFRESH_TOKEN__felix=...
-#     those could then be loaded up using 'pass' in a session env.
-accounts_felix_refresh_token=
-accounts_sylo_refresh_token=
 
 die () { echo >&2 "$@"; exit 1; }
 
@@ -44,10 +49,10 @@ if [[ -z "${user}" ]]; then
 	die "Account '${account}' not known. Available accounts are ${accounts[@]}"
 fi
 
-refresh_token_var="accounts_${account}_refresh_token"
+refresh_token_var="OAUTH_REFRESH_TOKEN_${account}"
 refresh_token="${!refresh_token_var}"
 if [[ -z "$refresh_token" ]]; then
-	die "Account '${account}' refresh token not found. Please obtain and set it first."
+	die "Account '${account}' refresh token not found. Please obtain and set it as $refresh_token_var first."
 fi
 
 oauth2.py \
